In [ ]:
# ============================================================
# STEP 1: DEFINE DATASET PATH
# ============================================================

# Store the location of the SmartPlate CSV dataset
INPUT_FILE = r"C:\Users\Aaditya babaso patil\Desktop\SmartPlate_Data_Mining_Project\data\smartplate_cafeteria_dataset.csv"

In [ ]:
# ============================================================
# STEP 2: LOAD DATASET
# ============================================================

# Read the CSV file and store it in a DataFrame
df = pd.read_csv(INPUT_FILE)

# Display confirmation message
print("✅ Dataset loaded successfully.")

✅ Dataset loaded successfully.

In [ ]:
# ============================================================
# STEP 3: CHECK DATASET SHAPE
# ============================================================

# df.shape[0] gives the number of rows
# df.shape[1] gives the number of columns

print("Number of Rows    :", df.shape[0])
print("Number of Columns :", df.shape[1])

Number of Rows    : 21900
Number of Columns : 19

In [ ]:
# ============================================================
# STEP 4: CHECK COLUMN NAMES
# ============================================================

# Display all column names with their serial numbers

for number, column in enumerate(df.columns, start=1):
    print(f"{number:02d}. {column}")

01. Date
02. Day_of_Week
03. Food_Item
04. Food_Category
05. Meal_Type
06. Quantity_Prepared
07. Quantity_Sold
08. Quantity_Wasted
09. Actual_Demand
10. Number_of_Students
11. Weather
12. Temperature
13. Special_Event_Flag
14. Holiday_Flag
15. Food_Cost_Per_Unit
16. Selling_Price_Per_Unit
17. Estimated_Cost_of_Waste
18. Unmet_Demand
19. Stockout_Flag

In [ ]:
# ============================================================
# STEP 5: DISPLAY FIRST 5 ROWS
# ============================================================

# head() displays the first 5 records of the dataset
df.head()

,Date,Day_of_Week,Food_Item,Food_Category,Meal_Type,Quantity_Prepared,Quantity_Sold,Quantity_Wasted,Actual_Demand,Number_of_Students,Weather,Temperature,Special_Event_Flag,Holiday_Flag,Food_Cost_Per_Unit,Selling_Price_Per_Unit,Estimated_Cost_of_Waste,Unmet_Demand,Stockout_Flag
0,1/1/2025,Wednesday,Buttermilk,Beverage,Beverages,41.07,39.09,1.98,39.09,171.55,Cloudy,21.2,1,1,0.8,1.5,1.58,0.0,0
1,1/1/2025,Wednesday,Coffee,Beverage,Beverages,41.47,40.10,1.37,40.10,171.55,Cloudy,21.2,1,1,0.8,1.5,1.09,0.0,0
2,1/1/2025,Wednesday,Lemon Juice,Beverage,Beverages,40.15,37.21,2.94,37.21,171.55,Cloudy,21.2,1,1,1.0,2.0,2.94,0.0,0
3,1/1/2025,Wednesday,Tea,Beverage,Beverages,77.84,57.53,20.31,57.53,171.55,Cloudy,21.2,1,1,0.5,1.0,10.15,0.0,0
4,1/1/2025,Wednesday,Aloo Paratha,Main Course,Breakfast,40.98,39.88,1.10,39.88,171.55,Cloudy,21.2,1,1,3.0,5.0,3.31,0.0,0

In [ ]:
# ============================================================
# STEP 6: CHECK DATA TYPES
# ============================================================

# Display the data type of every column
df.dtypes

Date                        object
Day_of_Week                 object
Food_Item                   object
Food_Category               object
Meal_Type                   object
Quantity_Prepared          float64
Quantity_Sold              float64
Quantity_Wasted            float64
Actual_Demand              float64
Number_of_Students         float64
Weather                     object
Temperature                float64
Special_Event_Flag           int64
Holiday_Flag                 int64
Food_Cost_Per_Unit         float64
Selling_Price_Per_Unit     float64
Estimated_Cost_of_Waste    float64
Unmet_Demand               float64
Stockout_Flag                int64
dtype: object

In [ ]:
# ============================================================
# STEP 7: CHECK MISSING VALUES
# ============================================================

# isnull() identifies missing values
# sum() counts missing values in each column

missing_values = df.isnull().sum()

print(missing_values)

# Calculate total number of missing values
total_missing = missing_values.sum()

print("\nTotal Missing Values:", total_missing)

Date                       0
Day_of_Week                0
Food_Item                  0
Food_Category              0
Meal_Type                  0
Quantity_Prepared          0
Quantity_Sold              0
Quantity_Wasted            0
Actual_Demand              0
Number_of_Students         0
Weather                    0
Temperature                0
Special_Event_Flag         0
Holiday_Flag               0
Food_Cost_Per_Unit         0
Selling_Price_Per_Unit     0
Estimated_Cost_of_Waste    0
Unmet_Demand               0
Stockout_Flag              0
dtype: int64

Total Missing Values: 0

In [ ]:
# ============================================================
# STEP 8: VALIDATE MISSING VALUES
# ============================================================

# If there are no missing values, validation passes
if total_missing == 0:

    print("✅ PASS: No missing values.")

else:

    print("⚠️ WARNING: Missing values found.")

✅ PASS: No missing values.

In [ ]:
# ============================================================
# STEP 9: CHECK DUPLICATE ROWS
# ============================================================

# duplicated() identifies duplicate records
# sum() counts the total number of duplicate rows

duplicate_rows = df.duplicated().sum()

print("Total Duplicate Rows:", duplicate_rows)

Total Duplicate Rows: 0

In [ ]:
# ============================================================
# STEP 10: VALIDATE DUPLICATE ROWS
# ============================================================

# Check whether the dataset contains duplicate records

if duplicate_rows == 0:

    print("✅ PASS: No duplicate rows found.")

else:

    print("⚠️ WARNING: Duplicate rows found.")

✅ PASS: No duplicate rows found.

In [ ]:
# ============================================================
# STEP 11: BASIC STATISTICAL SUMMARY
# ============================================================

# describe() provides statistics such as:
# count, mean, standard deviation, minimum, maximum, etc.

df.describe()

,Quantity_Prepared,Quantity_Sold,Quantity_Wasted,Actual_Demand,Number_of_Students,Temperature,Special_Event_Flag,Holiday_Flag,Food_Cost_Per_Unit,Selling_Price_Per_Unit,Estimated_Cost_of_Waste,Unmet_Demand,Stockout_Flag
count,21900.000000,21900.000000,21900.000000,21900.000000,21900.000000,21900.000000,21900.000000,21900.000000,21900.000000,21900.00000,21900.000000,21900.000000,21900.000000
mean,258.280402,240.416294,17.864131,242.129129,659.421479,26.505616,0.484932,0.230137,1.673333,2.94000,27.802528,1.712834,0.068037
std,215.492580,199.778347,22.880051,201.033572,385.309036,4.825452,0.499784,0.420930,0.876731,1.31573,36.987747,9.357268,0.251814
min,2.400000,2.300000,0.000000,2.300000,36.170000,13.500000,0.000000,0.000000,0.500000,1.00000,0.000000,0.000000,0.000000
25%,74.905000,69.817500,3.470000,70.240000,249.680000,23.100000,0.000000,0.000000,1.000000,2.00000,4.890000,0.000000,0.000000
50%,206.985000,193.470000,10.830000,194.990000,754.065000,27.300000,0.000000,0.000000,1.500000,2.75000,15.120000,0.000000,0.000000
75%,396.495000,370.467500,24.800000,372.820000,1000.240000,30.000000,1.000000,0.000000,2.000000,3.50000,37.962500,0.000000,0.000000
max,1427.980000,1238.840000,374.180000,1238.840000,1254.610000,36.400000,1.000000,1.000000,4.000000,6.50000,513.950000,180.140000,1.000000

In [ ]:
# ============================================================
# STEP 12: CHECK UNIQUE VALUES
# ============================================================

# Count the number of unique values in every column

for column in df.columns:

    print(
        f"{column}: "
        f"{df[column].nunique()} unique values"
    )

Date: 730 unique values
Day_of_Week: 7 unique values
Food_Item: 25 unique values
Food_Category: 3 unique values
Meal_Type: 5 unique values
Quantity_Prepared: 18057 unique values
Quantity_Sold: 17805 unique values
Quantity_Wasted: 5613 unique values
Actual_Demand: 17783 unique values
Number_of_Students: 723 unique values
Weather: 4 unique values
Temperature: 201 unique values
Special_Event_Flag: 2 unique values
Holiday_Flag: 2 unique values
Food_Cost_Per_Unit: 8 unique values
Selling_Price_Per_Unit: 11 unique values
Estimated_Cost_of_Waste: 7444 unique values
Unmet_Demand: 1264 unique values
Stockout_Flag: 2 unique values

In [ ]:
# ============================================================
# STEP 13: CHECK NEGATIVE VALUES
# ============================================================

# Select only numeric columns
numeric_columns = df.select_dtypes(
    include="number"
).columns

# Check each numeric column for negative values
for column in numeric_columns:

    negative_count = (df[column] < 0).sum()

    print(
        f"{column}: "
        f"{negative_count} negative values"
    )

Quantity_Prepared: 0 negative values
Quantity_Sold: 0 negative values
Quantity_Wasted: 0 negative values
Actual_Demand: 0 negative values
Number_of_Students: 0 negative values
Temperature: 0 negative values
Special_Event_Flag: 0 negative values
Holiday_Flag: 0 negative values
Food_Cost_Per_Unit: 0 negative values
Selling_Price_Per_Unit: 0 negative values
Estimated_Cost_of_Waste: 0 negative values
Unmet_Demand: 0 negative values
Stockout_Flag: 0 negative values

In [ ]:
# ============================================================
# STEP 14: DATASET INFORMATION
# ============================================================

# info() displays:
# - Number of rows
# - Column names
# - Non-null values
# - Data types
# - Memory usage

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21900 entries, 0 to 21899
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     21900 non-null  object
 1   Day_of_Week              21900 non-null  object
 2   Food_Item                21900 non-null  object
 3   Food_Category            21900 non-null  object
 4   Meal_Type                21900 non-null  object
 5   Quantity_Prepared        21900 non-null  float64
 6   Quantity_Sold            21900 non-null  float64
 7   Quantity_Wasted          21900 non-null  float64
 8   Actual_Demand            21900 non-null  float64
 9   Number_of_Students       21900 non-null  float64
 10  Weather                  21900 non-null  object
 11  Temperature              21900 non-null  float64
 12  Special_Event_Flag       21900 non-null  int64
 13  Holiday_Flag             21900 non-null  int64
 14  Food_Cost_Per_Unit       21900 non-null  float64
 15  Selling_Price_Per_Unit   21900 non-null  float64
 16  Estimated_Cost_of_Waste  21900 non-null  float64
 17  Unmet_Demand             21900 non-null  float64
 18  Stockout_Flag            21900 non-null  int64
dtypes: float64(10), int64(3), object(6)
memory usage: 3.2+ MB

In [ ]:
# ============================================================
# STEP 15: FINAL VALIDATION SUMMARY
# ============================================================

print("=" * 70)
print("FINAL VALIDATION SUMMARY")
print("=" * 70)

# Display important dataset validation results
print("Rows           :", df.shape[0])
print("Columns        :", df.shape[1])
print("Missing Values :", total_missing)
print("Duplicate Rows :", duplicate_rows)

======================================================================
FINAL VALIDATION SUMMARY
======================================================================
Rows           : 21900
Columns        : 19
Missing Values : 0
Duplicate Rows : 0

In [ ]:
# ============================================================
# STEP 16: FINAL VALIDATION RESULT
# ============================================================

# Dataset passes if there are:
# 1. No missing values
# 2. No duplicate rows

if total_missing == 0 and duplicate_rows == 0:

    print("\n" + "=" * 70)
    print("✅ DATASET VALIDATION PASSED")
    print("=" * 70)

    print(
        "The SmartPlate dataset is ready "
        "for further analysis."
    )

else:

    print("\n" + "=" * 70)
    print("⚠️ DATASET VALIDATION NEEDS ATTENTION")
    print("=" * 70)

    print(
        "Please check the missing values "
        "and duplicate rows."
    )

======================================================================
✅ DATASET VALIDATION PASSED
======================================================================
The SmartPlate dataset is ready for further analysis.